# Source: ack-consul/templates/server-disruptionbudget.yaml
# PodDisruptionBudget to prevent degrading the server cluster through
# voluntary cluster changes.
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: consul-server
  namespace: test
  labels:
    app: consul
    project: test
    component: server
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: consul
      project: test
      component: server
