apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: app-etcd-cluster
    app: etcd
  name: app-etcd-cluster
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: app-etcd-cluster-2379
    port: 2379
  - name: app-etcd-cluster-2380
    port: 2380
  selector:
    k8s-app: app-etcd-cluster
    app: etcd
